#!/bin/sh

set -eu

# shellcheck source=config.od
. ./config.od

# shellcheck shell=sh disable=SC2019
# shellcheck shell=sh disable=SC2018
container_name=$(uuidgen | tr 'A-Z' 'a-z')

docker_run_cmd() {
	set -- run -d --rm

	if [ -f local_settings.json ]; then
		set -- "$@" -v "$(pwd)/local_settings.json:/discord-bot/local_settings.json"
	fi

	set -- "$@" --name "$container_name" "$image_full"

	./docker_command "$@"
}

stop_container() {
	echo '✋ Stopping container...'
	./docker_command container stop "$container_name" >/dev/null 2>&1
}

start_container() {
	test -f .build_id || return

	image_full="${repo_local}/${image}:$(cat .build_id)"

	echo '🏁 Starting container...'
	docker_run_cmd > /dev/null
	( sleep 5 ; ./docker_command logs "$container_name"; echo '💡 ^C to stop' ) &
}

trap 'trap - 0; stop_container' 0

echo '🔄 Starting up...'

redo test
stop_container || true
start_container

while true; do
	echo '👁️ Waiting for changes...'
	watchman-wait . -p '*.do' '*.od' '*.tmpl' 'pipgrip.lock' '.build_id' \
	                   'start' '**/*.py'

	echo '🔄 Rebuilding...'
	if redo test; then
		stop_container
		start_container
	fi
done
