FROM       python:3-alpine@sha256:af8fef83397b3886ed93d2c81bf3b4e70d39c0789c1c6feb1ecb86ca9bc42a0a AS builder
SHELL      ["/bin/ash", "-e", "-o", "pipefail", "-c"]
RUN        apk --no-cache add build-base=0.5-r3 \
                              curl=7.86.0-r1 {{ .Env.TMPL_security_apk_builder | regexp.Replace "[[:space:]]+" " " }}
{{ if ne .Env.TMPL_finding_deps "" -}}
RUN        echo 'Cache buster: {{ uuid.V4 }}' && \
           pip install --disable-pip-version-check --no-cache-dir --no-deps \
                       {{ .Env.TMPL_python_dependencies_pipgrip | regexp.Replace "[[:space:]]+" " " }} && \
           pipgrip --lock --sort --no-cache-dir -vv requests 'discord.py<2.0' && \
           mv pipgrip.lock /tmp
{{ else -}}
# hadolint ignore=DL3059
RUN        curl -L '{{ .Env.TMPL_jo_dist_url }}' -o jo.tar.gz && \
           echo '{{ .Env.TMPL_jo_dist_sha256 }}  jo.tar.gz' | sha256sum -c && \
           tar xvf jo.tar.gz
WORKDIR    /jo-{{ .Env.TMPL_jo_version }}
RUN        ./configure && make && make install
# hadolint ignore=DL3059
COPY       pipgrip.lock /tmp
RUN        python -m venv /discord-bot && \
           /discord-bot/bin/pip install --disable-pip-version-check \
                                        --no-cache-dir --no-deps \
                                        wheel=={{ .Env.TMPL_python_wheel_version }} && \
           /discord-bot/bin/pip install --disable-pip-version-check \
                                        --no-cache-dir --no-deps \
                                        -r /tmp/pipgrip.lock
COPY       bot/ /discord-bot/bot/
WORKDIR    /discord-bot
RUN        python -m compileall bot
{{ end -}}
{{ if ne .Env.TMPL_finding_deps "" -}}
USER       nobody
{{ end -}}

{{ if eq .Env.TMPL_finding_deps "" }}
FROM       python:3-alpine@sha256:af8fef83397b3886ed93d2c81bf3b4e70d39c0789c1c6feb1ecb86ca9bc42a0a
{{ if ne .Env.TMPL_security_apk_runtime "" -}}
RUN        apk --no-cache add {{ .Env.TMPL_security_apk_runtime | regexp.Replace "[[:space:]]+" " " }}
{{ end -}}
ENV        APPTOKEN=unset
ENV        CHECKFORUPDATES=false
ENV        LANGUAGE=en-us
ENV        COMMANDPREFIX=!
ENV        DEBUG=false
ENV        SUPPESSWARNINGS=true
COPY       --from=builder /usr/local/bin/jo /usr/local/bin
COPY       --from=builder /discord-bot /discord-bot
COPY       start /discord-bot
RUN        chmod 0555 /discord-bot/start && \
           addgroup -S aarrr && \
           adduser -S -H -h /nonexistent -s /sbin/nologin \
                   -G aarrr -g 'Avast me lovelies' aarrr && \
           install -m 0600 -o aarrr -g aarrr /dev/null \
                                             /discord-bot/settings.json
USER       aarrr
ENTRYPOINT ["/discord-bot/start"]
{{ end -}}
