FROM       python:3-alpine@sha256:9f107fb8f0d64669f3cc857dd3b62e7f3b72e70b91a8f055868f1d0bad09cb84 AS builder
SHELL      ["/bin/ash", "-e", "-o", "pipefail", "-c"]
RUN        apk --no-cache add build-base=0.5-r2 curl=7.80.0-r0
# hadolint ignore=DL3059
RUN        curl -L '@JO_DIST_URL@' -o jo.tar.gz && \
           echo '@JO_DIST_SHA256@  jo.tar.gz' | sha256sum -c && \
           tar xvf jo.tar.gz
WORKDIR    /jo-@JO_VERSION@
RUN        ./configure && make && make install
# hadolint ignore=DL3059
RUN        python -m venv /discord-bot && \
           /discord-bot/bin/pip install --disable-pip-version-check \
                                        --no-cache-dir --no-deps \
                                        wheel==0.37.1 && \
           /discord-bot/bin/pip install --disable-pip-version-check \
                                        --no-cache-dir --no-deps \
                                        @PYTHON_DEPENDENCIES@
COPY       bot/ /discord-bot/bot/
WORKDIR    /discord-bot
RUN        python -m compileall bot

FROM       python:3-alpine@sha256:9f107fb8f0d64669f3cc857dd3b62e7f3b72e70b91a8f055868f1d0bad09cb84
ENV        APPTOKEN=unset
ENV        CHECKFORUPDATES=false
ENV        LANGUAGE=en-us
ENV        COMMANDPREFIX=!
ENV        DEBUG=false
ENV        SUPPESSWARNINGS=true
COPY       --from=builder /usr/local/bin/jo /usr/local/bin
COPY       --from=builder /discord-bot /discord-bot
COPY       start /discord-bot
RUN        chmod 0555 /discord-bot/start && \
           addgroup -S aarrr && \
           adduser -S -H -h /nonexistent -s /sbin/nologin \
                   -G aarrr -g 'Avast me lovelies' aarrr && \
           install -m 0600 -o aarrr -g aarrr /dev/null \
                                             /discord-bot/settings.json
USER       aarrr
ENTRYPOINT ["/discord-bot/start"]
