{{ define "split shellquote" -}}
  {{ if ne . "" -}}
    {{ " " }}{{ . | regexp.Split `\s+` | strings.ShellQuote -}}
  {{ end -}}
{{ end -}}

FROM       python:3-alpine@sha256:deb0f6327a7c0314470c76b3f92dca287b7aa138baabbd0259e2b6690e6b2dd6 AS builder
SHELL      ["/bin/ash", "-e", "-o", "pipefail", "-c"]
RUN        apk --no-cache add build-base=0.5-r3 \
                              curl=7.87.0-r1 {{- .Env.TMPL_security_apk_builder | tmpl.Exec "split shellquote" }}
{{ if ne .Env.TMPL_finding_deps "" -}}
RUN        echo 'Cache buster: {{ uuid.V4 }}' && \
           pip install --disable-pip-version-check --no-cache-dir --no-deps \
                       {{ .Env.TMPL_python_dependencies_pipgrip | tmpl.Exec "split shellquote" }} && \
           pipgrip --lock --sort --no-cache-dir -vv requests 'discord.py<2.0' {{- .Env.TMPL_security_python_dependencies | tmpl.Exec "split shellquote" }} && \
           mv pipgrip.lock /tmp
{{ else -}}
# hadolint ignore=DL3059
RUN        curl -L -o jo.tar.gz {{ .Env.TMPL_jo_dist_url | strings.ShellQuote }} && \
           echo {{ print .Env.TMPL_jo_dist_sha256 "  " "jo.tar.gz" | strings.ShellQuote }} | sha256sum -c && \
           tar xvf jo.tar.gz
WORKDIR    {{ print "/jo-" .Env.TMPL_jo_version | strings.Quote }}
RUN        ./configure && make && make install
# hadolint ignore=DL3059
COPY       pipgrip.lock /tmp
RUN        python -m venv /discord-bot && \
           /discord-bot/bin/pip install --disable-pip-version-check \
                                        --no-cache-dir --no-deps \
                                        wheel=={{ .Env.TMPL_python_wheel_version | strings.ShellQuote }} && \
           /discord-bot/bin/pip install --disable-pip-version-check \
                                        --no-cache-dir --no-deps \
                                        -r /tmp/pipgrip.lock
COPY       bot/ /discord-bot/bot/
WORKDIR    /discord-bot
RUN        python -m compileall bot
{{ end -}}
{{ if ne .Env.TMPL_finding_deps "" -}}
USER       nobody
{{ end -}}

{{ if eq .Env.TMPL_finding_deps "" }}
FROM       python:3-alpine@sha256:deb0f6327a7c0314470c76b3f92dca287b7aa138baabbd0259e2b6690e6b2dd6
{{ if ne .Env.TMPL_security_apk_runtime "" -}}
RUN        apk --no-cache add {{- .Env.TMPL_security_apk_runtime | tmpl.Exec "split shellquote" }}
{{ end -}}
ENV        APPTOKEN=unset
ENV        CHECKFORUPDATES=false
ENV        LANGUAGE=en-us
ENV        COMMANDPREFIX=!
ENV        DEBUG=false
ENV        SUPPESSWARNINGS=true
COPY       --from=builder /usr/local/bin/jo /usr/local/bin
COPY       --from=builder /discord-bot /discord-bot
COPY       start /discord-bot
RUN        chmod 0555 /discord-bot/start && \
           addgroup -S aarrr && \
           adduser -S -H -h /nonexistent -s /sbin/nologin \
                   -G aarrr -g 'Avast me lovelies' aarrr && \
           install -m 0600 -o aarrr -g aarrr /dev/null \
                                             /discord-bot/settings.json
USER       aarrr
ENTRYPOINT ["/discord-bot/start"]
{{ end -}}
